development:
  adapter: postgresql
  encoding: unicode
  database: peoplefindr_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: peoplefindr_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: peoplefindr_production
  pool: 5
